### PR TITLE
bug-fix: network creation process when its already created aka RESUME operation

### LINKED ISSUE #278: bug: network creation avoiding other dependent cloud resources when its found in `state_file`
# Describe 🐞
there's a syntax problem in Azure https://github.com/kubesimplify/ksctl/blob/main/internal/cloudproviders/azure/network.go#L18 here suppose the resource-group created and then any of the other resources regarding  not created , when we again use restart condition it will skip the all other components .  as we are just returning.
## Provider in effect
- Azure
# Reproduce 💻 ➡️  💻

# Possible Fix & Expected behavior🔧
instead after that use else condition also to check other resources such as subnet 

# Screenshots :framed_picture:

## Operating System
Windows , Linux , Mac

## ksctl version 
v1.1.2 Latest

# Additional context
Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl-docs/docs/contribution-guidelines/)

### PR DESCRIPTION
**Pull request by harisheoran**
# Related to Bug fixes or other types of fixes
fix: Bug #283 

If the resources are already created then also call the createvirtnet and createsubnet.

### CODE REVIEW

**Comment by dipankardas011** [comment]
@harisheoran please don't close PR as it makes the history cluttered

**Comment by harisheoran** [comment]
Got it man, this is my first time, I didn't know about it.

**Review by dipankardas011 — APPROVED** [review]
Nice thanks 👍🏼

**Comment by dipankardas011** [comment]
@harisheoran can you sign the commit using verified gpg key

**Comment by harisheoran** [comment]
Ok

**Comment by harisheoran** [comment]
> @harisheoran can you sign the commit using verified gpg key

Done

**Comment by dipankardas011** [comment]
@harisheoran can be squash and rebase your branch?

**Review by dipankardas011 — APPROVED** [review]
LGTM 🚀

**Comment by Horiodino** [comment]
hey @harisheoran can you remove this typo as the subnet is already deleted earlier, it should be virtnet otherwise, if some failure situation occurs it will give wrong print statement. like
```
skipped subnet already deleted", "name", subnet
subnet already deleted", "name", vnet
```

https://github.com/kubesimplify/ksctl/blob/525ce1fc2b43da6fb33cb8e5c85059de4d66d7f6/internal/cloudproviders/azure/network.go#L195C2-L225C52

**Comment by harisheoran** [comment]
> hey @harisheoran can you remove this typo as the subnet is already deleted earlier, it should be virtnet otherwise, if some failure situation occurs it will give wrong print statement. like
> 
> ```
> skipped subnet already deleted", "name", subnet
> subnet already deleted", "name", vnet
> ```
> 
> https://github.com/kubesimplify/ksctl/blob/525ce1fc2b43da6fb33cb8e5c85059de4d66d7f6/internal/cloudproviders/azure/network.go#L195C2-L225C52

ok, Why I have to print "vnet" as we are trying to delete subnet in that fucntion

**Comment by Horiodino** [comment]
subnet and virtnet are two different modules

**Comment by harisheoran** [comment]
> subnet and virtnet are two different modules

Ok, but why do I have to print about "vnet" in deleting subnet

**Comment by dipankardas011** [comment]
@harisheoran praful meant by refactoring this line https://github.com/kubesimplify/ksctl/blob/525ce1fc2b43da6fb33cb8e5c85059de4d66d7f6/internal/cloudproviders/azure/network.go#L225

to correct the wrong word used!

it should be 
```go
log.Print("virtual network already deleted", "name", vnet)
```

**Comment by Horiodino** [comment]
yep

**Comment by dipankardas011** [comment]
rest of the code looks fine, once you have commited and rebased. I am happy to merge it
BTW, thanks for working on this issue ❤️

**Comment by harisheoran** [comment]
> @harisheoran praful meant by refactoring this line
> 
> https://github.com/kubesimplify/ksctl/blob/525ce1fc2b43da6fb33cb8e5c85059de4d66d7f6/internal/cloudproviders/azure/network.go#L225
> 
> to correct the wrong word used!
> 
> it should be
> 
> ```go
> log.Print("virtual network already deleted", "name", vnet)
> ```

Ok got it now, Thank you.
Praful link was showing highlights of "DeleteSubnet" function, that's why I asked.

**Comment by harisheoran** [comment]
> rest of the code looks fine, once you have commited and rebased. I am happy to merge it BTW, thanks for working on this issue ❤️

ok, Thank you for the support (even on silly questions)

**Review by Horiodino — APPROVED** [review]

**Pull request merged**
