### PR TITLE
fix(api): environment variable for providers credentials

### LINKED ISSUE #6: [API](*) Option to AUTH without using `ksctl cred` instead using ENV VAR
## Task
Create a hierarchy of authentication methods
1. Check if specific providers Environment variables have values in them
2. If not then go for standard or present method to read from `~/.ksctl/cred/*.json`

### PR DESCRIPTION
**Pull request by dipankardas011**
# Tasks description :construction: 🔧 
Fixes the Provider credential fetch from the Environment variables and file.
improves the printing needed for the credentials to work good!

- [x] Closes #86 Continuation of this PR
- [x] Closes #6 Parent Issue

# Solution :heavy_check_mark:
added the environment  variable check before accessing the file containing the cred
if specific env not set try to fetch them from file If not found then panic i.e. exit code 1

# Note to reviewers :notebook:

### CODE REVIEW

**Comment by dipankardas011** [comment]
@Manda-supraja26 from here you can work

**Comment by dipankardas011** [comment]
I am facing issues wrt to reading the environment variables

**Comment by Manda-supraja26** [comment]
> I am facing issues wrt to reading the environment variables

can i know which env is having issue ,civo or azure?

**Comment by dipankardas011** [comment]
> > I am facing issues wrt to reading the environment variables
> 
> can i know which env is having issue ,civo or azure?

In azure one

**Comment by dipankardas011** [comment]
I need to check for civo

**Comment by dipankardas011** [comment]
this is how civo is working 
image

**Comment by dipankardas011** [comment]
and azure one is having difficulties

**Comment by Manda-supraja26** [comment]
okay i will work on azure one

**Comment by dipankardas011** [comment]
@Manda-supraja26 @AvineshTripathi this issue is resolved

**Comment by dipankardas011** [comment]
@dipankardas011 add the log for which enviromnet variables are missing!

**Review by dipankardas011 — COMMENTED** [review]
LGTM

**Review by AvineshTripathi — APPROVED** [review]

**Pull request merged**
