### PR TITLE
refresh(branch): updating the branch `dev`

### PR DESCRIPTION
**Pull request by dipankardas011**
# Tasks / Issue :construction: 🔧 

- [x] None

# Solution :heavy_check_mark:

# Screenshots :framed_picture:

# Note to reviewers :notebook:

### CODE REVIEW

**Comment by dipankardas011** [comment]
@AvineshTripathi you can approve this pr and add the mergable label before 12 pm and check if it runs only on 12 ? or does it run anytime?

**Comment by AvineshTripathi** [comment]
Done doing it right now!

**Comment by AvineshTripathi** [comment]
@dipankardas011 added mergable label, when you say approve the pr do you mean merge it?

**Comment by dipankardas011** [comment]
> @dipankardas011 added mergable label, when you say approve the pr do you mean merge it?

thinking of the following steps (context is this project):
1. lgtm -> anyone who is reviewing can approve the changes  and add lgtm label
2. mergable -> once all the things are in place then we can add this label for github action to automatically merge to respective branch
> also its a corn job which can merge branches whose target is `main, dev`

**Review by AvineshTripathi — APPROVED** [review]

**Pull request merged**
