### PR TITLE
Added azure managed cluster creation support

### PR DESCRIPTION
**Pull request by AvineshTripathi**
Signed-off-by: AvineshTripathi <avineshtripathi1@gmail.com>

In order to create a managed cluster you would need following things 
- Subscription ID - you need to add this when running the `ksctl cred .....` command for azure 
- Tenant ID, Client ID, Client Secret - you will need to export the these variables as env variables like below 

export AZURE_TENANT_ID=<your tenant id>
export AZURE_CLIENT_ID=<your client id>
export AZURE_CLIENT_SECRET=<your client secret>

For this PR only managed cluster creation is supported. Deletion is manual for now 

NOTE: there is an extra file named `akstesting.go` which is temporary and will be helpful in understanding the flow

### CODE REVIEW

**Comment by dipankardas011** [comment]
@AvineshTripathi i have resolved do check

**Comment by AvineshTripathi** [comment]
am resolving testing stuff for now till then you can review the code

**Comment by dipankardas011** [comment]
# Tasks :construction:
## maganed k8s support
- you might be taking a look Azure go sdk and also 
## HA k8s support
### Infrastructure procurement
- Resource Group
- 1 VM for database (choose the size most approproate for mysql)
- 1 VM for Loadbalancer also *ElasticIP* for it
- `n` VMs for controlplane nodes
- `m` VMs for workerplane nodes
- Security groups
- keypair

### Steps
**Step 1**: Create SSH keypair and upload
**Step 2**: Create Database VM and block all `incoming traffic` from outside world only allow incoming traffic from private IP and that to for Mysql port `3306`
**Step 3**: Create Loadbalancer VM and install HAproxy for configuring we nned the all the controlplane nodes private IPs and only allow `6443` port from anywhere
**Step 4**: Create Controlplane nodes and install k3s server with right set of ports ( Refer Kubernetes docs or K3s docs )and allow ports
**Step 5**: Create workerplane nodes and install k3s agents

### additional info
if possible make the worker nodes private VMs (no public IP)
if possible make the database private
worker nodes, database to be utilizing the initialization scripts (a.k.a. user-data script)
controlplane and loadbalancer will require ssh support to login and execute scripts

@AvineshTripathi

**Comment by dipankardas011** [comment]
@AvineshTripathi there are some conflicts could you make this branch in the ksctl repo as I can then work to fix some changes

**Comment by AvineshTripathi** [comment]
@dipankardas011 check new aks branch

**Comment by dipankardas011** [comment]
@AvineshTripathi could you delete this PR and create another one using the branch you specifed above

**Comment by AvineshTripathi** [comment]
Now you too can delete and create PR so you can do accordingly

**Comment by dipankardas011** [comment]
- #67

**Pull request closed without merging**
