### PR TITLE
HA Azure firewall rules.

### LINKED ISSUE #124: enhancement: Add firewall rules for the HA clusters
# Why do we need it?

# What it will bring?

### PR DESCRIPTION
**Pull request by Horiodino**
# Tasks description :construction: 🔧 

- [ ] Closes #124

# Solution :heavy_check_mark:

NONE

# Note to reviewers :notebook:
i accidentally add some function but now i have removed from api/aws so it wont be a problem.
for now everything is fine i just removed the additional structs from aws , only added firewalls rules 
as per the issue.
for making sure its ok you can check below files 

[Delete utils.go](https://github.com/kubesimplify/ksctl/pull/125/commits/5745316ed388fa9315b306093577fc8256fbc479)

[Update main.go](https://github.com/kubesimplify/ksctl/pull/125/commits/3cb4d6a6caace1183985c1846fdcb065142fafa7)

[Update README.md](https://github.com/kubesimplify/ksctl/pull/125/commits/8246662f6434b043d6be68cf7ce518a8f5e0160f)
NONE

- [ ] Ran Unit Test locally
- [ ] Tested the website locally

### CODE REVIEW

**Review by AvineshTripathi — COMMENTED** [review]
Can we make the Port range or any IP suggested to here to dynamic or maybe question should be "should we make it dynamic"?

**Comment by dipankardas011** [comment]
One thing we can do
We can deny all hosta and ports and then add allow rules
But still have test whether it works or not (if we don't define rules does it defaults to deny all in security rules)?

**Comment by Horiodino** [comment]
> One thing we can do We can deny all hosta and ports and then add allow rules But still have test whether it works or not (if we don't define rules does it defaults to deny all in security rules)?

i think it will be same even we deny all ports ,  because all ports are blocked default by azure vms .

**Comment by dipankardas011** [comment]
@Horiodino now you can work on this

**Pull request closed without merging**
