### PR TITLE
enhancement: Add firewall rules for the HA cluster on azure

### PR DESCRIPTION
**Pull request by Horiodino**
tasks done :  exposed port 22 for controlplane from public 
and port 22 for loadbalancer and database and workernodes in private
  
6443 allow ingress (public) for loadbalancer
6443 ingress (privateip) for controlplane and workerplane

allowed port of MYSQL for ingress and egress
to private IP only

### CODE REVIEW

**Comment by dipankardas011** [comment]
@Horiodino why are all the lines changes?

**Comment by Horiodino** [comment]
> @Horiodino why are all the lines changes?

well i dont now but , i just forked from main repo and added changes, does the line changes ?? i meant any code change ? or any error ?

**Comment by dipankardas011** [comment]
@Horiodino sorry but we cannot review this PR as it might be your IDE has changed for the reformated the entire file

**Comment by dipankardas011** [comment]
@Horiodino can you create a new PR with fix?

**Comment by Horiodino** [comment]
> @Horiodino can you create a new PR with fix?

yes i will create pr with fix tomorrow  will be fine .  :+1:

**Pull request closed without merging**
