### PR TITLE
feat: Addition of AWS support #17

### PR DESCRIPTION
**Pull request by Horiodino**
# Tasks description

```[tasklist]
### Tasks
- [ ] #17 
``` 

# Solution
Add Ksctl aws support.

```[tasklist]
### Tasks
- [ ] milestones or sub-task which needs to be coverted
``` 

# Note to reviewers

- [ ] Ran Unit Test locally
- [ ] Tested the website locally
- [ ] Checked [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)

### CODE REVIEW

**Comment by dipankardas011** [comment]
@Horiodino Are you using aws-go-sdk version 2 as now most of them uses it

**Comment by Horiodino** [comment]
> @Horiodino Are you using aws-go-sdk version 2 as now most of them uses it

I am using version 1 .

**Comment by Horiodino** [comment]
no problem I will switch to version 2

**Comment by Horiodino** [comment]
> @Horiodino Are you using aws-go-sdk version 2 as now most of them uses it

Done 👍

**Comment by dipankardas011** [comment]
@Horiodino make sure you regularly fix the conflicts

**Comment by dipankardas011** [comment]
@Horiodino do resolve the conflicts

**Comment by Horiodino** [comment]
> @Horiodino do resolve the conflicts

🫡

**Comment by dipankardas011** [comment]
@Horiodino you should use a different branch name other than main
So that it will be easier for you to resolve conflicts

**Comment by dipankardas011** [comment]
@Horiodino Can you mention about this PR in the next bi-weekly meet

**Pull request closed without merging**
