### PR TITLE
[Docs] Added Roadmap

### PR DESCRIPTION
**Pull request by dipankardas011**
added process map of the project

Signed-off-by: Dipankar Das <dipankardas0115@gmail.com>

# Tasks / Issue :construction:

- [x] #40 
- [x] #29 
```
To add more info about the roadmap and current status of the project
```

# Solution :heavy_check_mark:
```
mermaid in markdown
```

# Screenshots :framed_picture:

Tuesday 22 November

# Note to reviewers :notebook:

do merge it after the above **PR** is merged!

### CODE REVIEW

**Comment by dipankardas011** [comment]
```diff
+ some-text +
- some-text -
# some-text #
* some-text *
```

**Comment by dipankardas011** [comment]
```md
<span style="color: black; background-color: red;">DONE</span>
<span style="color: white; background-color: black;">NO PLANS</span>
<span style="color: white; background-color: blue;">BACKLOG</span>
```
@AvineshTripathi the color to text not working

**Comment by dipankardas011** [comment]
github markdown is not rendering

**Comment by dipankardas011** [comment]
```diff
+ 
- 
# 
!

```
some of the color options

**Comment by AvineshTripathi** [comment]
I am not sure how this works

**Comment by dipankardas011** [comment]
then for now we can mention in text

**Comment by dipankardas011** [comment]
@AvineshTripathi you can mark it mergable if lgtm

**Pull request merged**
