### PR TITLE
Host-Key Verification

### PR DESCRIPTION
**Pull request by riteshsonawane1372**
# Tasks / Issue :construction:
Fix code scanning alert - Use of insecure HostKeyCallback implementation 
- #47
Removed InsecureHostKeyCallback and added known_host

# Solution :heavy_check_mark:
```
```

# Screenshots :framed_picture:

# Note to reviewers :notebook:

### CODE REVIEW

**Comment by dipankardas011** [comment]
@riteshsonawane1372 are you still working ?

**Comment by dipankardas011** [comment]
Also make sure you update your branch with main branch

**Comment by riteshsonawane1372** [comment]
no

**Comment by dipankardas011** [comment]
Okay will be closing it

**Pull request closed without merging**
